### ISSUE TITLE
String and Statement colors

### ISSUE THREAD

**Issue by lazywei** [junegunn/seoul256.vim#19]
Hi,

I'm encountering a weird issue on syntax highlighted. Please refers to https://github.com/othree/yajs.vim/issues/18#issuecomment-76393663 and its following comments. It seems the Statement and String's color are the same in my terminal vim. However, I do check the seoul256.vim's color, the Statement and String has different value... do you have any idea about this?

Thanks.

**Comment by junegunn** [comment]
Check the output of:
- `:verbose hi String`
- `:verbose hi Statement`

**Comment by lazywei** [comment]
```
String         xxx ctermfg=109 guifg=#98BCBD
        Last set from ~/dotfiles/vim/plugged/seoul256.vim/colors/seoul256.vim

Statement      xxx term=bold ctermfg=108 gui=bold guifg=#98BC99
        Last set from ~/dotfiles/vim/plugged/seoul256.vim/colors/seoul256.vim
```

**Comment by junegunn** [comment]
You see, the colors are clearly different, so it's not an issue of this color scheme.
