### ISSUE TITLE
Hi Guy~  Would support airline style for you colorscheme?~

### ISSUE THREAD

**Issue by DemonCloud** [junegunn/seoul256.vim#21]
Just like gruvbox 

![screenshot](https://cloud.githubusercontent.com/assets/7436361/7917749/100c18ae-08bf-11e5-85d2-95e9cb6c7b33.png)

**Comment by junegunn** [comment]
If what you're asking is if I'm going to write an airline theme for seoul256, then the answer is no, I don't use airline. But if you're going to write one, I won't stop you :)
