### ISSUE TITLE
vim-airline support

### ISSUE THREAD

**Issue by shinzui** [junegunn/seoul256.vim#22]
Do you have a corresponding [vim-airline](https://github.com/bling/vim-airline) scheme?

**Comment by junegunn** [comment]
Sorry, no, I don't use airline.

**Comment by martin-damien** [comment]
For information, you can use *zenburn* theme, it match very well :

``` vim
let g:airline_theme='zenburn'
```

**Comment by jbkopecky** [comment]
I have made my own seoul-256 airline theme [here](https://github.com/jbkopecky/dotfiles/blob/master/vim/autoload/airline/themes/seoul256.vim).

**Comment by shinzui** [comment]
@jbkopecky thank you.

**Comment by lowski** [comment]
@jbkopecky thanks!

**Comment by rpereira** [comment]
@jbkopecky The link is broken. I took a look at your repository and couldn't find it. Also, I've noticed that you may have a tmux theme as well. Is there any chance you can share them? Thanks.

**Comment by jbkopecky** [comment]
Hey, sorry I dropped Airline for a simpler status line.
I created a [Gist](https://gist.github.com/jbkopecky/a2f66baa8519747b388f2a1617159c07) so you can access the file anyhow.

For the tmux status line, I shamelessly stole @junegunn 's [one](https://github.com/junegunn/dotfiles/blob/master/tmux.conf#L109) and [modified](https://github.com/jbkopecky/dotfiles/blob/master/tmux.conf#L101) it a little to use only 16 colors, with [base16 xresources](https://github.com/chriskempson/base16-xresources) colors conventions.

**Comment by rpereira** [comment]
@jbkopecky Thanks for your time.

Cheers.
