### ISSUE TITLE
vim can set font bold

### ISSUE THREAD

**Issue by JoouChou** [junegunn/seoul256.vim#24]
Hi everyone,
I used seoul256 scheme just now, and it is pretty.
But I find I can not set font bold, like this:
![image](https://cloud.githubusercontent.com/assets/8896124/9993706/ac95f53e-60ab-11e5-8cdf-2e539f6bd68a.png)

Moreover, I find my statusline missed..

Thank you!

**Comment by junegunn** [comment]
Hi, I don't use GUI vim, so I'm not sure if I can help you. But your problem with `set guifont=bold` does not seem like an issue of this particular color scheme. Try it with other color schemes, and you'll probably run into the same problem. Statusline not showing is also not an issue of this color scheme and I can't reproduce in any way. I suggest that you comment out most of your vimrc, and gradually uncomment lines to see what's causing the problem.
