### ISSUE TITLE
'ExtraWhitespace' clashes with 'vim-better-whitespace' plugin

### ISSUE THREAD

**Issue by bruno-** [junegunn/seoul256.vim#25]
Hi,
first of all thank you for all your work for the dev community. I'm using a lot of your work (this plugin, vim-plugin, fzf, vim-easy-align and the list goes on).

I'm reporting what I think is an issue, and has been bothering me for a long time now: the `ExtraWhitespace` highlight definition. I find the definition in this plugin provides too little contrast. I barely see it in my files.

I'm also using a "dedicated" plugin for this [vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace). That plugin defines a screaming red color for `ExtraWhitespace` and I like that one more (actually it hurts my eyes, but I remove it faster that way).
But, since `seoul256` defines this highlight, `vim-better-whitespace` plays nice and doesn't overwrite it.

Could this be implemented in some other way to let dedicated plugins take precedence?
If not, would you consider removing the `ExtraWhitespace` highlight definition?

Thanks!

**Comment by junegunn** [comment]
No, I won't. This is just a color scheme and changing the name of it or removing it will simply break backward-compatibility and there's no other way. I think you should instead ask the author of vim-better-whitespace to add an option to force-override it.
