### ISSUE TITLE
Support for bold/italic Markdown text

### ISSUE THREAD

**Issue by iKevinY** [junegunn/seoul256.vim#28]
Hi Junegunn — I recently started using Vim, and now I'm looking to incorporate it into my prose-writing workflow. (goyo and limelight are awesome!) Would you be open to adding bold and italic Markdown support to seoul256, similar to [pencil.vim](https://github.com/reedes/vim-colors-pencil/blob/master/colors/pencil.vim#L298)?

![pencil colourscheme](https://cloud.githubusercontent.com/assets/2434728/13550843/d9a33f5c-e2db-11e5-8cc9-e4d332bfb042.png)

**Comment by junegunn** [comment]
Sorry for the late reply. I'll take a look later in the day.

**Comment by junegunn** [comment]
<img width="690" alt="screen shot 2016-03-13 at 2 05 24 am" src="https://cloud.githubusercontent.com/assets/700826/13724177/164a0564-e8c0-11e5-95e7-85c1d48fe2e4.png">

Bold and italic seem to work in GVim without any change. Am I missing something?

**Comment by iKevinY** [comment]
Ah, looks like you're right. There appears to be an issue with my Vim configuration where changing colour schemes removes all text formatting. Thanks again for all the Vim tools you've put up on GitHub!
