### ISSUE TITLE
Colors colder than in screenshot

### ISSUE THREAD

**Issue by randrej** [junegunn/seoul256.vim#32]
Is it my imagination, or are the colors in the readme's screenshot warmer than the theme colors really are? I'd love to have that 'warmer' option without using redshift.

For instance, take a look at this:
![screenshot_2016-10-27_20-50-43](https://cloud.githubusercontent.com/assets/3741879/19780855/16b12e12-9c87-11e6-9ef1-905b570975fb.png)

In the screenshot:
left: readme screenshot; middle: nvim-qt; right: nvim in urxvt (256)

Line selecton background colors (teal) are:
readme scrot = #327173 (50, 113, 115)
nvim-qt (rgb) = #007173 (0, 113, 115)
nvim in urxvt (256) = #005F5F (0, 95, 95), though that's expected

Am I missing something? Were You using redshift or such when taking the scrot?

**Comment by junegunn** [comment]
> Were You using redshift or such when taking the scrot?

No, I just took the screenshots in iterm2. Colors also look exactly the same on MacVim.

The colors in your screenshot indeed look pretty different. I have no idea why.

**Comment by randrej** [comment]
There seems to be a disparity between MacOS and Linux interpretation of 24bit colors: Apple (iterm2 and macvim, at least) seem to interpret the data as Apple (or Adobe) RGB, and my Linux install interprets it as sRGB.

I'll try to make a branch with colors corrected to sRGB values (at least the RGB ones)...
