### ISSUE TITLE
No Haskell support?

### ISSUE THREAD

**Issue by rpereira** [junegunn/seoul256.vim#33]
Hello @junegunn,

First of all great work with this theme, it is really awesome. I've been using it since last week, but I just opened an Haskell file and almost everything is white :( Does this colorscheme support Haskell? What other languages does it support?

![screen shot 2016-11-13 at 9 58 50 am](https://cloud.githubusercontent.com/assets/3859158/20244827/ff7fa36e-a987-11e6-93f2-16b7ef9c9c52.png)

Thanks.

**Comment by junegunn** [comment]
Usually, a color scheme only defines colors for the default set of highlight groups. See `:help highlight-default`. And it's the syntax plugin that is responsible for mapping the syntax groups of a particular language to those default groups. Consider installing a better syntax highlighting plugin for haskell such as https://github.com/neovimhaskell/haskell-vim.

**Comment by rpereira** [comment]
I have that plugin installed @junegunn. Before switching to seoul256 I was using Solarized and that highlights were correct. Hence, I thought it would be a problem related to the colorscheme.

**Comment by junegunn** [comment]
I can confirm that haskell files are properly highlighted when the plugin is also installed.

**Comment by rpereira** [comment]
Ok, thanks for your help @junegunn.
