### ISSUE TITLE
Wrong highlighting for javascript.jsx

### ISSUE THREAD

**Issue by rpereira** [junegunn/seoul256.vim#34]
Hello @junegunn,

Here's an example of wrong highlighting for `javascript.jsx`. It is correctly highlighted with other colorschemes.

![screen shot 2016-11-16 at 4 28 32 pm](https://cloud.githubusercontent.com/assets/3859158/20425668/7628c452-ad73-11e6-8acf-d083bde1c8e3.png)

**Comment by junegunn** [comment]
Which syntax plugin do you use?

**Comment by rpereira** [comment]
@junegunn I'm using [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) [mxw/vim-jsx](https://github.com/mxw/vim-jsx).

**Comment by junegunn** [comment]
Other colorschemes I have (molokai, tomorrow) also use different colors for opening and closing tags just like seoul256. If you don't like it, you should probably contact the author of vim-jsx.
