### ISSUE TITLE
Source command fails for seoul256-light (no space between 'source' and filename)

### ISSUE THREAD

**Issue by janlazo** [junegunn/seoul256.vim#38]
- Platform
  - [X] Windows
  - [ ] Mac
  - [ ] Linux
- Vim
  - [X] Terminal
  - [X] Gvim

Patch from PR #36 broke the source command ([seoul256-light.vim#L67](https://github.com/junegunn/seoul256.vim/blob/master/colors/seoul256-light.vim#L67)) in Windows because fnameescape() did not handle the network drive (ex. `C:\`).
Relative paths and absolute paths without the network drive work (ex. `/Vim/vim80/colors/desert.vim` with `set shellslash`).

Steps to Reproduce Issue:
1. Open terminal vim or Gvim
2. `:colorscheme seoul256-light`

Result: `E492: Not an editor command: silent source<filepath>`

Workaround:
- add back the space (ex. `'silent source ' . <file>`)

**Comment by junegunn** [comment]
Fixed, sorry for the troubles.

**Comment by janlazo** [comment]
It works now.
Thanks for the quick fix.
