### ISSUE TITLE
Highlight Neovim's Whitespace group

### ISSUE THREAD

**Issue by adriaanzon** [junegunn/seoul256.vim#43]
Recently a `Whitespace` highlight group was added to Neovim (https://github.com/neovim/neovim/pull/6367).

It got linked to `NonText` by default, which results in the difference as shown in these screenshots https://github.com/neovim/neovim/pull/6367#issuecomment-292634652 (the two bottom most screenshots)

For seoul256, `Whitespace` should link to `SpecialKey` to make it the same color as before. However you may also want to take advantage of this addition, and highlight `Whitespace` with less contrast than `SpecialKey` on `Neovim`.

**Comment by junegunn** [comment]
I just changed the color of SpecialKey.
