### ISSUE TITLE
Distribute colorscheme with Vim?

### ISSUE THREAD

**Issue by chrisbra** [junegunn/seoul256.vim#46]
there is an [issue](https://github.com/vim/vim/issues/1665) open in the vim repository, to distribute more colorschemes with Vim. Would you kindly give your permission to distribute this colorscheme with Vim?

**Comment by junegunn** [comment]
I don't mind as long as you follow the license. One thing you might want to note is that `seoul256-light.vim` actually loads `seoul256.vim`.

https://github.com/junegunn/seoul256.vim/blob/master/colors/seoul256-light.vim#L36

**Comment by chrisbra** [comment]
okay, I sent it to vim-dev for inclusion https://groups.google.com/d/msg/vim_dev/7MioBIC5GR8/tCC_WJJ_AgAJ
However I won't be able to send updates, as I don't know, when it is stable enough or when there is a release version.
