### ISSUE TITLE
Popups in NeoVim are illegible

### ISSUE THREAD

**Issue by lynndylanhurley** [junegunn/seoul256.vim#60]
Hi @junegunn, thank you for this amazing colorscheme. I've been using it for years now and I've never considered switching.

I'm getting this when using [`coc.nvim`](https://github.com/neoclide/coc.nvim):

<img width="811" alt="Screen Shot 2019-03-28 at 8 11 45 PM" src="https://user-images.githubusercontent.com/468037/55202560-e7a77880-5195-11e9-8492-a4d1440fac69.png">

The text in the popup is very difficult to read.

**Comment by lynndylanhurley** [comment]
I added this line to my `.vimrc` and it improved the situation:

```viml
hi link CocFloating markdown
```

**Comment by nree** [comment]
thanks!... i wonder if it's possible to get a different bg color than the editor though? I liked the visual separation of the popup box being a different color. But of course the pink with light fg color was unreadable.

And I wonder what's a good airline theme for seoul256 ? I'm using gruvbox but it uses pink for the gitgutter.

**Comment by junegunn** [comment]
b68f403 should help.
