### ISSUE TITLE
seoul256.vim + coc.nvim color scheme issues

### ISSUE THREAD

**Issue by adidottxt** [junegunn/seoul256.vim#65]
hi there!

first off, thank you for your work with this theme among others -- big fan of this theme along with goyo + limelight and a bunch of other vim plugins you've worked on.

I recently installed coc.nvim for autocompletion + suggestions and noticed that seoul256.vim's color scheme for suggestions + descriptions within coc.nvim are hard to read. I've attached a couple of screenshots as an example.

![Screenshot from 2020-01-31 16-08-50](https://user-images.githubusercontent.com/29982667/73574764-851da980-4444-11ea-80d4-b11e2a893fec.png)

![Screenshot from 2020-01-31 16-11-46](https://user-images.githubusercontent.com/29982667/73574770-88189a00-4444-11ea-977d-cf51bbef20a4.png)

is there something I can do to help fix this?

thanks again!

**Comment by junegunn** [comment]
Do you have the latest version of seoul256.vim?

https://github.com/junegunn/seoul256.vim/commit/b68f4032c49b64065072b449dc0f0f1f30616d8d

**Comment by adidottxt** [comment]
@junegunn sorry for the late response with this; I believe so. I've run `:PlugUpdate` and `seoul256.vim` is already up to date. I've double checked the `colors/seoul256.vim` file as well and the lines added in https://github.com/junegunn/seoul256.vim/commit/b68f4032c49b64065072b449dc0f0f1f30616d8d are present in my local installation.

**Comment by adidottxt** [comment]
I found that changing
`call s:hi('CocFloating', [s:dark_fg, s:light_fg], [s:dark_bg - 2, s:light_bg - 2])`
to 
`call s:hi('CocFloating', [s:dark_fg, s:light_fg], [s:dark_bg + 2, s:light_bg + 2])`
made this more usable (see below)

![Screenshot from 2020-02-25 10-38-46](https://user-images.githubusercontent.com/29982667/75262810-0d306e00-57bb-11ea-96be-298efd477729.png)

If you'd like, I could submit a PR to make this update? Or a different color based on the seoul256 color scheme. Let me know.

**Comment by junegunn** [comment]
So you seem to use a low `g:seoul256_background` value. The problem here is that by subtracting 2 from it, the value "underflows" and an invalid color is chosen. I should have addressed it.
