### ISSUE TITLE
git commits could have more semantic colors…

### ISSUE THREAD

**Issue by evantravers** [junegunn/seoul256.vim#8]
Traditionally, additions are green, deletions are red, and modified lines are some neutral-ish color like yellow/purple/whatever.

Right now… deletions are yellow, additions are purple… I'm not quite sure what modified is.

Is this something I should modify in another plugin, or what?

**Comment by nealmcb** [comment]
I found this page in a search for how colorblind people could change the colors used for diff output.  I didn't find details here, but I did figure it out, so for posterity, this is what works for me, and how to change it to something that works for you....

In `~/.gitconfig`, add a stanza like this:

    [color "diff"]
      meta = red bold
      frag = magenta bold
      old = blue bold
      new = green bold

See http://git-scm.com/docs/git-config for more details.
