### ISSUE TITLE
Black on black text for popup list

### ISSUE THREAD

**Issue by Starefossen** [junegunn/seoul256.vim#81]
Love seoul256 ❤️  Any thought on how I can set the color for the popup command list? It's a little hard to read the options except for the one selected.

https://github.com/Starefossen/dotfiles/blob/12414d047b343dd4aca976898a264b692f2e6066/.config/nvim/init.vim#L23-L26

```
" seoul256 theme
let g:seoul256_background = 233
color seoul256
autocmd ColorScheme * :highlight LineNr ctermbg=233
```

<img width="357" alt="Screenshot 2022-08-17 at 21 14 32" src="https://user-images.githubusercontent.com/968267/185224023-8a9fb1bf-39e2-4e3b-a49b-a1948b224415.png">

**Comment by junegunn** [comment]
Any better now?

**Comment by Starefossen** [comment]
Awesome 😍 Worked like a charm 💯 

![Screenshot 2022-08-18 at 10 37 25](https://user-images.githubusercontent.com/968267/185350451-61bb729e-170f-428c-8934-defe05ca3ab7.png)
