### ISSUE TITLE
16 colors to use

### ISSUE THREAD

**Issue by greduan** [junegunn/seoul256.vim#9]
In a 16 color setup, what would be the Seoul colors that would go along with the 16 terminal colors?

Also, I am using [Termite](https://github.com/thestinger/termite) so I can also re-define any of the 256 colors, if that would make the terminal version more accurate then if you could please provide those as well, that'd be cool. ;)

Thank you very much! :)

**Comment by polyzen** [comment]
Hey @greduan, do you still have those termite settings?

**Comment by greduan** [comment]
@polyzen Not handy, but you could probably find them in my [dotfiles repo](https://github.com/greduan/dotfiles).

You may find this useful to find it: http://mislav.uniqpath.com/2014/02/hidden-documentation/

**Comment by polyzen** [comment]
@greduan, did they actually ever make it into that repo? Wasn't able to find it

**Comment by greduan** [comment]
Maybe https://github.com/greduan/dotfiles/blob/b96e6a1b511a3a3bb4c3ff5aa77da61654f95c41/config/termite/config

Not sure if ti contains the Gruvbox colors though.

**Comment by polyzen** [comment]
Huh, I wonder how you found that. I still have to finish reading that article :p Thanks!

**Comment by greduan** [comment]
`git log -S termite` and I went through each commit to find the file. :)

**Comment by polyzen** [comment]
Thank you for your help :)

**Comment by greduan** [comment]
No problem. :)
